### ISSUE TITLE
Convert plcc.py into a Python package

### ISSUE THREAD

**Issue by StoneyJackson** [ourPLCC/plcc#121]
To help with redesigns, it would be helpful to organize functionality across multiple files (making clear the boundaries and independence of components). Converting plcc.py into a package would help with this and gets us closer to #119 .

This would change the way you call it. Currently, as a script, we call it like this...

```bash
$ python3 path/to/plcc.py
```

Once converted into a package, we would call it like this...

```bash
$ python3 -m plcc
```

This requires that it's parent directory is in Python's path (PYTHONPATH). After #119 , this is automatic. Until then, the PLCC scripts can set this just before calling plcc, something like this

```bash
PYTHONPATH=/path/to/parent/of/plcc python3 -m plcc
```

PLCC's scripts can do this by using relative paths from their current location as described in #120 .

## Code impact

The codebase would need to be reorganized as follows:

```
plcc/                      Rename src/ to plcc/
    bin/                    Move scripts (scan, parse, etc.) to bin/
    lib/                     Move Std/ and lib/jackson/*.jar here.
    __init__.py        Makes plcc/ a Python package.
    __main__.py     Rename plcc.py as __main__.py which makes plcc/ executable.
    ...                       Other Python scripts are organized under plcc/ .
```

Scripts and __main__.py (currently plcc.py) would need to update the way they find the location of resources (e.g., Std/).
Scripts would need to be updated to set PYTHONPATH and CLASSPATH correctly.

## User impact

This would break existing PLCC installations as LIBPLCC would point to src/ which no longer exists.
Users would need to reinstall PLCC when they upgrade.

**Comment by jashelio** [comment]
I played around with these Python features a bit. On the one hand, I read that __init__.py has not been required since Python3.3. On the other hand, I suggest it be used to do the necessary imports, whereas __main__.py contains the simple code line(s) to start everything running. No biggie; just my preference.

**Comment by StoneyJackson** [comment]
@jashelio

Wow, didn't know `__init__.py` was no longer required. Thanks for letting me know. Based on some quick reads, I don't get the impression that they want everyone to stop using it. At this point, we don't use them to control imports, just to signal that a directory is really a Python package. So we could remove them.

I added `__main__.py` to allow the `plcc` package to be "executable". That is, so that we can run `python3 -m plcc`. Currently `__main__.py` is the old `plcc.py`. The goal, after this change, is to start breaking down and organizing functionality into more independent packages and modules leaving a relatively thin, bootstrapping `__main__.py`. I think this matches your preference. Let me know if I miss understood.
