### ISSUE TITLE
Missing Bash/plcc

### ISSUE THREAD

**Issue by StoneyJackson** [ourPLCC/plcc#14]
`Batch/plcc.bat` exists. Not sure why there isn't a `Bash/plcc`.

**Comment by fosler** [comment]
I don't remember there being a Batch directory, but if there is one, it's probably only for Windows installations, and all of the batch files in this directory end in ".bat". I never created a Bash directory: all of the bash scripts should be at the same level as plcc.py.

**Comment by StoneyJackson** [comment]
@fosler I created the separate directories. But that sounds like a bad move. So I'll put them back and then look at your copy for the original plcc bash script.

**Comment by StoneyJackson** [comment]
After moving all the scripts to the top-level project directory (on my local system; I haven't pushed any changes yet), the top-level project directory feels muddy. All the command scripts are mixed in with meta files like CHANGELOG.md. LICENSE, and CONTRIBUTING.md. And these meta files are conventionally placed in the root of a project, and many tools (including GitHub) look for them there to provide some nice automation features. So I'm thinking about adopting another common practice and moving the true source files of the project into a subdirectory named `src/`. The new directory structure would look like this.

```bash
.
├── CHANGELOG.md
├── CONTRIBUTING.md
├── LICENSE
├── PLCC-paper.pdf
├── README.md
├── dev
│   ├── Release
│   │   ├── Dockerfile
│   │   └── release.bash
│   ├── build.sh
│   ├── docker-compose.yml
│   └── release.sh
├── examples
│   ├── arbno
│   ├── eee
│   ├── foobar
│   ├── print
│   ├── this
│   └── tst
└── src
    ├── Std
    │   ├── ILazy.java
    │   ├── IMatch.java
    │   ├── IScan.java
    │   ├── ITrace.java
    │   ├── Parser.java
    │   ├── Rep.java
    │   ├── Scan.java
    │   ├── Token.pattern
    │   ├── Token.template
    │   └── Trace.java
    ├── VERSION
    ├── parse
    ├── parse.bat
    ├── plcc
    ├── plcc.bat
    ├── plcc.py
    ├── plccmk
    ├── plccmk.bat
    ├── rep
    ├── rep-t
    ├── rep-t.bat
    ├── rep.bat
    ├── scan
    └── scan.bat
```

This change would also require a change to the installation instructions when direct users to define the LIBPLCC environment variable as `/path/to/plcc/src/` and to place that same path in the PATH environment variable.

Does anyone see a problem with this or object to it?

**Comment by jashelio** [comment]
Stoney,

I share your concern wrt the clutter in the top directory. However we have to make sure this is clean for our students, who must set their PATH variables correctly. I was already going to propose some modifications to the scripts, so maybe I should be in charge of making sure they work, IF you move them.

Jim

**Comment by StoneyJackson** [comment]
@jashelio I would be happy to have you test things before they are merged into master! I'll add you as a review to any pull-request related to this.

I think there are some subtle problems with putting all the scripts (Bash and Batch) into one directory. I seam to remember one of my students getting errors when running the bash scripts under Windows via a git-bash (MinGW linux emulator) environment. By keeping them separate and telling students to put the right directory in their PATH I was hoping to control which scripts are being executed by operating system.

Let me run some experiments on my wife's Windows laptop and see what I can come up with.

**Comment by StoneyJackson** [comment]
Tests complete. We can put Bash and Batch scripts in the same directory, and it doesn't cause any problems for Windows.

I think it used to. And I think the problem was that Python 3 was installed as `python.exe` on Windows and `python3` on Linux. There is evidence of this difference in the `plcc` bash script and the `plcc.bat` batch script. `plcc` invokes `python3 plcc.py`, and `plcc.bat` invokes `python plcc.py`. So when a Windows user invoked `plcc` through git-bash,  `python3 plcc` failed because `python3` didn't exist on Windows.

It looks like Python installers on Windows are now creating a symlink/shortcut or an alias from python3.exe to python.exe. So now either works.

I've create a pull request that reorganizes the files https://github.com/ourPLCC/plcc/pull/18 .

**Comment by jashelio** [comment]
I made a few small changes to the shell scripts in this branch. See commit message. Not tested in my copy of the repo.

**Comment by StoneyJackson** [comment]
@jashelio I tested the bash scripts under plcc-in-docker. They work! I can't easily run the Windows batch scripts (I have to convince my wife to let me use her laptop; and she's back to work). I inspected all of your changes and they look correct to me (but then, I'm not a bash expert; but I did look up things that I wasn't sure of). So maybe we could just assume they are good until we get a bug report from a student using windows.

Are we ready to merge #18?

**Comment by jashelio** [comment]
I think I'm ready to merge. I hope we don't have problems with the students getting the code with git instead of downloading a zip file. We shall see!

I made a few edits. Check them if you want to make sure.

Jim

**Comment by StoneyJackson** [comment]
@jashelio Students can still get a zip. In fact, the proposed instructions for installation has them downloading a zip and installing it. See https://github.com/ourPLCC/plcc/pull/18#issuecomment-667600236 .

**Comment by jashelio** [comment]
My mistake. Turns out I was reading the instructions intended for us!

**Comment by fosler** [comment]
My bad, too. Sorry for the overreaction...

**Comment by StoneyJackson** [comment]
No worries. I'm just glad you all are so engaged and diligent in protecting the integrity of the tool and course material!

**Comment by StoneyJackson** [comment]
:tada: All done here! :tada:

Closing.
