### ISSUE TITLE
Parse and Rep

### ISSUE THREAD

**Issue by fosler** [ourPLCC/plcc#32]
In VERSION 3.0.0, `Parse` and `Rep` both invoke `main` static method in `ProcessFiles` using a `parseOnly` parameter that distinguishes between just parsing (`Parse`, with `parseOnly=true`) and parsing and running (`Rep`, with `parseOnly=false`). In `ProcessFiles`, the `main` method calls a `run()` static method that uses an `if` statement that invokes either `$ok()` or `$run()` on the parse tree (an instance of `_Start`), depending on the value of `parseOnly`.

I don't like using `if` statements if they can be avoided using subclassing, so I recommend that we change `Rep` and `Parse` so that they are subclasses of `ProcessFiles`, and then they can appropriately call the right action -- `$ok()` or `$run()` -- without needing to pass a flag. This will not have any effects on behavior; it simply makes better sense from an OO point of view.

Oh, and I have taken the two very similar code blocks in ProcessFiles and factored them into a single method, `processFile`, which reduces the code size and helps to maintain consistency.

QUESTION: Instead of printing "OK" when using `Parse` to indicate a successful parse, how about just carrying out the parse and then printing nothing at all? If there is a parse error, a `PLCCException` will still show up. This would make it consistent with Unix/Linux, where silence means success. It's a simple matter to make this change: just have the default `$ok()` method do nothing in the `_Start` class. If a user wants different behavior, simply redefine `$ok()` in the start symbol class to whatever you want, such as printing "OK" to get the current behavior.

These changes are not quite bug fixes but can be considered minor, so I suggest a VERSION of 3.1.0.

**Comment by jashelio** [comment]
> On Aug 12, 2021, at 11:35 AM, fosler ***@***.***> wrote:
> 
> 
> ...I don't like using if statements if they can be avoided using subclassing, so I recommend that we change Rep and Parse so that they are subclasses of ProcessFiles, and then they can appropriately call the right action -- $ok() or `$run() -- without needing to pass a flag. This will not have any effects on behavior; it simply makes better sense from an OO point of view.

I agree; this sounds good.

> 
> QUESTION: Instead of printing "OK" when using Parse to indicate a successful parse, how about just carrying out the parse and then printing nothing at all? If there is a parse error, a PLCCException will still show up. This would make it consistent with Unix/Linux, where silence means success. It's a simple matter to make this change: just have the default $ok() method do nothing in the _Start class. If a user wants different behavior, simply redefine $ok() in the start symbol class to whatever you want, such as printing "OK" to get the current behavior.

I prefer sticking with OK. With all the new stuff the students learn, it is reassuring to see some kind of positive message at the end. I would be in favor of it being even larger, like "parse completed successfully".

Jim

**Comment by fosler** [comment]
All,

What drove me to suggest dropping the default "OK" was running this, in the OBJ language directory:

     java -cp Java Parse Prog/*

What I got was a mountain of lines containing "OK", except for one PLCCException line (which was expected). This just looked horribly "noisy".

OTOH, one can always redefine the "$ok()" method in the Program class to do nothing, which I guess is perfectly OK (<-- pun intended). Jim's comment about the benefit of printing a positive message seems perfectly justifiable. Let's leave it as-is. (I prefer "OK" to the even more noisy "parse completed successfully".)

I also want to suggest adding a '-v' (for "verbose") flag on the Parse/Rep command line. Setting this flag turns on printing the name of the command-line file in which the current expression is being parsed/evaluated, using the name "stdin" when reading from System.in. Here is an example from the OBJ language:

Without the '-v' switch:

     java -cp Java Rep Prog/oe
     c
     1
     0
     1
     --> .<c>even?(6)
     1

With the '-v' switch:

     java -cp Java Rep -v Prog/oe
     [Prog/oe]c
     [Prog/oe]1
     [Prog/oe]0
     [Prog/oe]1
     --> .<c>even?(6)
     [stdin]1

The '-v' switch is particularly useful when there are several files on the command line and you need to find the one where a particular error occurs. This is a simple addition and does not break prior behaviors.

Tim

**Comment by StoneyJackson** [comment]
> In VERSION 3.0.0, `Parse` and `Rep` both invoke `main` static method in `ProcessFiles` using a `parseOnly` parameter that distinguishes between just parsing (`Parse`, with `parseOnly=true`) and parsing and running (`Rep`, with `parseOnly=false`). In `ProcessFiles`, the `main` method calls a `run()` static method that uses an `if` statement that invokes either `$ok()` or `$run()` on the parse tree (an instance of `_Start`), depending on the value of `parseOnly`.
> 
> I don't like using `if` statements if they can be avoided using subclassing, so I recommend that we change `Rep` and `Parse` so that they are subclasses of `ProcessFiles`, and then they can appropriately call the right action -- `$ok()` or `$run()` -- without needing to pass a flag. This will not have any effects on behavior; it simply makes better sense from an OO point of view.
> 
> Oh, and I have taken the two very similar code blocks in ProcessFiles and factored them into a single method, `processFile`, which reduces the code size and helps to maintain consistency.


👍  Sounds like a good refactoring (i.e., not a breaking change or a new or improved feature).


> QUESTION: Instead of printing "OK" when using `Parse` to indicate a successful parse, how about just carrying out the parse and then printing nothing at all? If there is a parse error, a `PLCCException` will still show up. This would make it consistent with Unix/Linux, where silence means success. It's a simple matter to make this change: just have the default `$ok()` method do nothing in the `_Start` class. If a user wants different behavior, simply redefine `$ok()` in the start symbol class to whatever you want, such as printing "OK" to get the current behavior.
>


Either is reasonable.

Another option: print "OK" on success by default (as it is now), and provide a `-q` and/or `--quit` option that would silence output on success (still print error messages though).


> These changes are not quite bug fixes but can be considered minor, so I suggest a VERSION of 3.1.0.

Sure.

**Comment by StoneyJackson** [comment]
@fosler To get this in this upstream project, you should do the following in the root of your local clone:

```bash
git switch main
git pull
git switch -c whatever-name-for-the-new-work
```

Now your local clone is ready to receive your changes. For example, you could copy them over like you did last time...

```bash
cp -r path/to/your/copy ./src
```

Then stage, commit, and push your new branch.

```bash
git add .
git commit -m "a nice title for your changes"
git push -u origin whatever-name-for-the-new-work
```

Navigate to the link that is printed by the last command to create the merge request. Then we can review your changes there.

**Comment by StoneyJackson** [comment]
#33 resolves this issue. Closing.
