### ISSUE TITLE
Final newline missing in some Java source files

### ISSUE THREAD

**Issue by fosler** [ourPLCC/plcc#41]
In `plcc.py`, the line containing `return str` in the `getCode` procedure should `return str + '\n'` instead. The lack of a final newline in Java source files is not considered an error, but some editors may notice its absence. The absence of a newline does not happen with Java source files automatically generated from BNF grammar lines.

**Comment by StoneyJackson** [comment]
Fixed in https://github.com/ourPLCC/plcc/commit/05c0908dcf49bffb5ddcb41ff37ef98a539a8e34
