### ISSUE TITLE
Python 3.11 deprecates pipes

### ISSUE THREAD

**Issue by StoneyJackson** [ourPLCC/plcc#49]
Source: https://docs.python.org/3/library/pipes.html

We'll need to update to `subprocess` before we can bump to Python 3.13.

**Comment by fosler** [comment]
Do we use pipes in plcc.py? Ick! If so, do we need to instrument plcc.py so
it will know which version is being used and to act accordingly? Double
ick!!

**Comment by fosler** [comment]
Ah, I see it now -- it's the preprocessor thang, the "PP" flag. I added
this at the request of someone (Jim???) but I have never *ever* used it.
Does anyone use it?? Maybe we should just ditch the preprocessor feature so
we don't run into this particular Python issue. (Don't multiply entities
beyond necessity...)

**Comment by jashelio** [comment]
I’m not at home right now.I cannot recall asking for a preprocessor flag. Maybe it was something Maheen needed for her project?Is there any way to search comments in GitHub to see if we ever discussed this addition?JimSent from my iPhoneOn Aug 17, 2023, at 17:43, fosler ***@***.***> wrote:﻿
Ah, I see it now -- it's the preprocessor thang, the "PP" flag. I added

this at the request of someone (Jim???) but I have never *ever* used it.

Does anyone use it?? Maybe we should just ditch the preprocessor feature so

we don't run into this particular Python issue. (Don't multiply entities

beyond necessity...)



On Thu, Aug 17, 2023, 5:12 PM Stoney Jackson ***@***.***>

wrote:

**Comment by StoneyJackson** [comment]
Commits are here https://github.com/ourPLCC/plcc/commits/main

FYI, this thread is on our GitHub issue tracker. I add issues as I find problems so that we/I can eventually sort them out. I'm not in a hurry. In particular, things are really ramping up for the start of Fall. So as soon as I get the Workshop proposal out, I'll be unresponsive for a week or two.

**Comment by StoneyJackson** [comment]
I did some email archeology on this topic. Below is what I found. Interestingly, it sounds like this was suggested for the include feature requested in #55 . So if we keep this, then maybe we don't need that.

From @fosler 

```
I have a slightly newer version of plcc.py ... This version allows for setting up a preprocessor command (like 'cpp -P') so you can use #includes, a feature that was suggested by a colleague at RIT who is using the PLCC material. I now allow for underscores in identifiers and token names, which is no big deal, but was also suggested by my colleague.
```

From me

```
I love the idea of the preprocessor!
```

From @fosler 

```
Regarding the preprocessor stuff:

I have a "PP" flag defined in plcc.py that, when set to a command string, will run all of the generated code through the given preprocessor command as it writes the Java code to the generated files in the Java directory. I have used the command string 'cpp -traditional-cpp -P', but you can use any command string, like 'sed', as a stdin/stdout filter to modify the code. If the PP flag is not given, no preprocessing is done.

I also added a :top to the top of all of the generated Java files, so you can do something like this:

*:top # the stuff bracketed by the '%%%' markers will appear at the top of ALL generated Java files
%%%
// Stoney Jackson wrote this
// comment comment blah blah
%%%

If you want to put

     #include "foo"

at the top all of the Java files and use the preprocessor to include "foo" in all of your files, do this:

# this sets the preprocessor command
!PP=cpp -traditional-cpp -P

*:top
%%%
#include "foo"
%%%

You can, of course, put an #include at the top of individual files as well, instead of using the wildcard '*'.

I forgot to mention that if you have a Java file defined like this:

JJJ
%%%
...
%%%

you can "comment out" the entire file by doing this:

JJJ:ignore!
%%%
...
%%%
```

**Comment by StoneyJackson** [comment]
If we want to keep the preprocessor feature, we can switch from Python's pipes to [Python's subprocess library](https://docs.python.org/3/library/subprocess.html#module-subprocess).

**Comment by StoneyJackson** [comment]
**AGREED** Vacate the PP feature and remove the Python pipes dependency.
