### ISSUE TITLE
Add option to Parse.java to print AST in JSON

### ISSUE THREAD

**Issue by StoneyJackson** [ourPLCC/plcc#53]
Parent issue: #52 

## Design decisions that need to be made

- What should JSON format be?
- What should option name be?
- Add option to ProcessFiles.java?
- Implement as an ITrace?

**Comment by StoneyJackson** [comment]
## What should [the] JSON format be?

We should consider using [Jackson](https://github.com/FasterXML/jackson) (no relation to me). It serializes POJOs (plain old Java objects) into JSON format.

On the other end, we should look at [Jsonic](https://github.com/OrrBin/Jsonic). It deserializes JSON into instances of given classes.

The question is, are the two compatible? Can the JSON generated by Jackson be read by Jsonic? If so, this could be easy. If not, we may need to programmatically massage the output of Jackson's output so that it is suitable for Jsonic.

If these work, then we don't have to invent a JSON format. They may also save us from writing a lot of code.

**Comment by StoneyJackson** [comment]
## Implement as an ITrace?

I don't think this will work (at least it won't be easy). Instead, I think we'll need to implement a new class that inherits from ProcessFiles, named something like JsonTree, that's like Parse but uses Jackson to produce JSON of the parsed tree.

## What should option name be?

1. `--tree=json`
2. `--json`
3. `-j`

The first is probably overkill at the moment since we are implementing only a single output format.

The third is a little vague.

The second is probably the best if possible.

---

If we want this to run as an option to Parse (i.e., `parse --json`)...

Options of Parse are handled by ProcessFiles, which Parse inherits. Assuming JsonTree also inherits from ProcessFiles, the Parse implementation would need to construct a JsonTree and use it instead of itself. But the JsonTree would need to ignore this option, lest it infinitely, recursively constructs JsonTree objects. The problem is that the base class ProcessFiles is where options are handled, but we need the `--json` option to be handled in the subclasses. So add a method toJsonTree(argv) in ProcessFiles that constructs and returns a JsonTree by default. Then override this method in JsonTree to return `this`. Call this method from ProcessFiles when handling the `--json` option.

**Comment by StoneyJackson** [comment]
@Rarity-Belle @WilliamBowery Please explore/try-out [Jackson](https://github.com/FasterXML/jackson) and [Jsonic](https://github.com/OrrBin/Jsonic) and see if they will work for us.

**Comment by StoneyJackson** [comment]
Issue: Jackson is a 3rd party Java package. To use 3rd party Java packages, it's best to use a package manager to resolve dependencies. In Java, that's Maven or Gradle. Gradle is the newer of the two. So @Rarity-Belle and @WilliamBowery are figuring out how to set up Gradle with PLCC.

**Comment by StoneyJackson** [comment]
Gradle is a bad idea because it would add a dependency for end users (Gradle).

Instead, we're going to try to ship the jar files for Jackson with PLCC and then include them in the classpath when compiling and running plcc stuff. This would not require an extra dependency.

**Comment by jashelio** [comment]
The Parse program builds an AST from classes that PLCC creates. The user can only enhance those classes. If we want to display the AST visually, and the the tree already exists as a collection of instances of PLCC-created classes, why not have PLCC add code to those classes to display the tree?

Also, these notes don't say why viewing the AST in JSON is useful.

**Comment by fosler** [comment]
How exactly do you want the AST to be printed? Running Parse with the '-t'
option prints the AST in a rather klutzy way...

**Comment by StoneyJackson** [comment]
@jashelio See #52 for rationale. Short answer: we need to export the AST from a parser in Java to a Rep-loop in Python.

**Comment by StoneyJackson** [comment]
@fosler

The goal:

```bash
cat program | java -cp Java Parse --json | python -m plcc.rep
```

If we use the output of `-t` we'll have to write a custom parser in Python to read it. We believe it will be easier to use a Java library to dump the AST as JSON, and use a Python library to read the AST as JSON.

Once we can dump ASTs in JSON, then we can use plethora of tools and libraries that work with JSON.
