### ISSUE TITLE
v4.0.0 requires upgrade to JDK 13 or 14

### ISSUE THREAD

**Issue by StoneyJackson** [ourPLCC/plcc#61]
Our docs (https://github.com/ourPLCC/plcc/wiki/Native-PLCC-Installation) say that the minimum version of JDK is 11. The new generated Token.java requires JDK 13 (or 14?) because it uses the new switch expression.

```java
        String what = "??";
        switch(match.tokType) {
            case SKIP -> what = "skip";
            case TOKEN -> what = "token";
            case LINE_TOGGLE -> what = "token (line toggle)";
        }
```

It's probably reasonable to update to more recent version of JDK anyway. Red Hat will end its support of OpenJDK 11 in 2024. So maybe it makes sense to jump to the next long-term-support (LTS) version of 17. Or the most recent LTS, 21.  Red Hat's support for 17 ends in 2027; support for 21 ends in 2028 (https://en.wikipedia.org/wiki/Java_version_history). Since 17 was released in Sept 2023, maybe we should go with 17.

Thoughts?

**Comment by jashelio** [comment]
Let's go right to 21, since it's a major release. Also, a picayune language point: The code you show in your example could be a switch _expression_, and you could use the default tag to assign the "??" value.

**Comment by StoneyJackson** [comment]
@fosler: revert to switch-statement.
@StoneyJackson : Need to run two sets of tests: one with minimum java one with lastest.
@StoneyJackson : Check our docs.

**Comment by fosler** [comment]
Token.pattern reverted to statement-based switch statement. VERSION
updated to v4.0.1.
