### ISSUE TITLE
Invalid escape sequences in Python 3.12 are now SyntaxWarnings (to become SyntaxErrors)

### ISSUE THREAD

**Issue by StoneyJackson** [ourPLCC/plcc#66]
They are warnings for now. But probably an easy fix, and the fix should be backwards compatible.

![Screenshot 2023-11-03 at 9 36 26 PM](https://github.com/ourPLCC/plcc/assets/1394670/40e4962e-40b1-4ddb-b7a7-bd36ee99f81e)

**Comment by StoneyJackson** [comment]
See second bullet in https://docs.python.org/3/whatsnew/3.12.html#other-language-changes

**Comment by jashelio** [comment]
Yes. Apparently it's an easy fix. Just make the literal strings raw by prepending them with an 'r'.
