### ISSUE TITLE
Improve installer

### ISSUE THREAD

**Issue by StoneyJackson** [ourPLCC/plcc#89]
I'm thinking about creating an "installer/env.bash" that generates the code one should evaluate in their .bashrc. Then, we tell folks to add a single line to their .bashrc

```bash
eval "$(path/to/plcc/installer/env.bash)"
```

This is better because then upgrades are easier. For example, if we need an additional environment variable installed, we can make the change in env.bash, and when the user upgrades, no changes are needed to their .bashrc.

I know I've seen tools that do this (I don't remember which; maybe pyenv?), but I never understood why until now.

**Comment by jashelio** [comment]
Is _path/to/plcc/installer_ the same as the path where plcc will be installed? I'm thinking about the fact that **env.bash** may need to be edited, depending on where plcc is installed. Granted, for the fully automated installation techniques, this is not a problem.

**Comment by StoneyJackson** [comment]
@jashelio You are correct. The installer will print the eval statement with the correct path. So when you run this:

```bash
/bin/bash -c "$(curl -fsSL https://github.com/ourPLCC/plcc/raw/main/installer/install.bash)"
```

It will print

```bash
# Please add the following to the end of $HOME/.bashrc
eval "$(path/to/plcc/installer/env.bash)"
```

But with the correct path to env.bash.

I'm tempted to make the instructions for installing using the installer to be this:

```bash
/bin/bash -c "$(curl -fsSL https://github.com/ourPLCC/plcc/raw/main/installer/install.bash)" >> $HOME/.bashrc
```

That way the user doesn't need to edit .bashrc themselves, but can remove `>> $HOME/.bashrc` if they would prefer to update it manually. I think most would just run the one-liner.
