### ISSUE TITLE
Remove  `include` in grammar files?

### ISSUE THREAD

**Issue by StoneyJackson** [ourPLCC/plcc#99]
The classic `include` has created some problems for the new Python feature. Since `#include` was more recently added, does it obsolete `include`? And if it does, removing `include` is a possible solution to the problems it creates for the new Python feature. Plus it would simplify the language.

I'm creating this issue so we don't forget about it and so we have a place tot discuss this issue, share our results, track its progress, etc.

---

## Working Plan

1. In https://github.com/ourPLCC/languages

    - [x] Manually test replacing `include` with `#include` works for several languages.
    - [x] Develop an automated testing strategy.
    - [x] Write one or two automated tests for each language.
    - [x] Replace `include` with `#include` for each language in https://github.com/ourPLCC/languages . (Ensure tests pass.)

2. In https://github.com/ourPLCC/course

    - [x] Carefully replace `include` with `#include`

3. In https://github.com/ourPLCC/plcc

    - [x] ~Deprecate `include` (?)~
    - [x] Remove `include`

**Comment by StoneyJackson** [comment]
@jashelio @fosler

1. Should we remove the original `include` in favor of `#include`?
2. If yes to (1), should we just remove `include` functionality, or should we follow a deprecation strategy?

**Comment by jashelio** [comment]
Normally I feel that deprecation is the more professional alternative. However, as the most active user of PLCC, I’m OK with either decision you make, Stoney. I have no problems editing any grammar file I need, should the older feature be removed.Jim On Apr 18, 2024, at 9:13 AM, Stoney Jackson ***@***.***> wrote:﻿
@jashelio @fosler

Should we remove the original include in favor of #include?
If yes to (1), should we just remove include functionality, or should we follow a deprecation strategy?

**Comment by fosler** [comment]
I prefer deprecation, especially since there is a chance someone may run
across an old PLCC specification and simply not notice that it uses
'include' instead of '#include'. I don't feel strongly about this, however.

**Comment by StoneyJackson** [comment]
AGREED: remove `include` on 4/19/2024 without deprecation.
